apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nano-gateway.fullname" . }}-config
  labels:
    {{- include "nano-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
